name: F100_STRIKER
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build APK with Buildozer
        uses: digon88/buildozer-action@v1.2
        with:
          save_buildozer_cache: false
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TEAM_F100_APK
          path: bin/*.apk
