name: F100_STRIKER_BUILD
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build APK with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          save_buildozer_cache: false
      - name: Upload Finished APK
        uses: actions/upload-artifact@v2
        with:
          name: TEAM_F100_APK
          path: bin/*.apk
